export const CATEGORY_GET = 'CATEGORY_GET';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';
export const CATEGORY_REMOVE = 'CATEGORY_REMOVE';

export const GET_TOTAL_BUDGET = 'GET_TOTAL_BUDGET';